#!/bin/bash

TMP=/usr/share/yunohost/yunohost-config

# Samba
if [ ! -f /etc/yunohost/yunohost.conf ] || [ $(grep samba /etc/yunohost/yunohost.conf | cut -d= -f2) = "no" ];
then
        cp $TMP/samba/* /etc/samba/
        cp $TMP/smbldap-tools/* /etc/smbldap-tools/
	mkdir -p /home/yunohost.samba/{share,public,profiles,netlogon}
        chmod 770 /home/yunohost.samba/share /home/yunohost.samba/public
        chmod 777 /home/yunohost.samba/profiles
        chmod 600 /etc/smbldap-tools/smbldap_bind.conf
fi

service slapd restart
