#!/bin/bash

TMP=/usr/share/yunohost/yunohost-config/moulinette

#Firewall
grep -q "UPNP:" /etc/yunohost/firewall.yml > /dev/null 2>&1
if [[ $? -eq 0 ]] || [ ! -f /etc/yunohost/firewall.yml ];
then
	cp $TMP/firewall.yml /etc/yunohost/
fi

# Service list
if [ ! -f /etc/yunohost/services.yml ];
then
	cp $TMP/services.yml /etc/yunohost/
fi

rm -rf /var/cache/moulinette/*
update-rc.d yunohost-api defaults
service yunohost-api restart

# Reload SSOwat conf if obsolete
if [ -f /etc/ssowat/conf.json ];
then
    grep -q "ynhadmin" /etc/ssowat/conf.json
    if [[ $? -eq 0 ]]
    then
        yunohost tools ssowatconf
    fi
fi
