#!/bin/bash

TMP=/usr/share/yunohost/yunohost-config/moulinette

# Udiskie
ps aux | grep udiskie | grep -qv grep
if [[ ! $? -eq 0 ]];
then
    pip install udiskie==0.8.0
    update-rc.d udiskie defaults
    service dbus restart > /dev/null 2>&1
    if [[ $? -eq 1 ]]; then
        rm -f /var/run/dbus/system_bus_socket
        service dbus restart
    fi
    service udiskie restart
fi

# Allow users to access /media directory
if [ ! -d /etc/skel/media ];
then
        mkdir -p /media
	ln -s /media /etc/skel/
fi

#Firewall
grep -q "UPNP:" /etc/yunohost/firewall.yml > /dev/null 2>&1
if [[ $? -eq 0 ]] || [ ! -f /etc/yunohost/firewall.yml ];
then
	cp $TMP/firewall.yml /etc/yunohost/
fi

# Service list
if [ ! -f /etc/yunohost/services.yml ];
then
	cp $TMP/services.yml /etc/yunohost/
fi

rm -rf /var/cache/moulinette/*
update-rc.d yunohost-api defaults
service yunohost-api restart

# Reload SSOwat conf if obsolete
if [ -f /etc/yunohost/installed ];
then
    yunohost app ssowatconf
fi
