#!/bin/sh
# postinst script for yunohost-config-metronome

set -e

# summary of how this script can be called:
#        * <postinst> `configure' <most-recently-configured-version>
#        * <old-postinst> `abort-upgrade' <new version>
#        * <conflictor's-postinst> `abort-remove' `in-favour' <package>
#          <new-version>
#        * <deconfigured's-postinst> `abort-deconfigure' `in-favour'
#          <failed-install-package> <version> `removing'
#          <conflicting-package> <version>
# for details, see http://www.debian.org/doc/debian-policy/ or
# the debian-policy package

case "$1" in
    configure)
        if [ ! -f "/etc/yunohost/yunohost.conf" ] || [ $(grep metronome /etc/yunohost/yunohost.conf | cut -d= -f2) = "no" ]; then
            # Backup current conf file
            if [ -f "/etc/metronome/metronome.cfg.lua" ]; then
                mv /etc/metronome/metronome.cfg.lua /etc/metronome/metronome.cfg.lua.dist-old
            fi

            # Copy new conf file and update it
            cp /usr/share/yunohost/yunohost-config/metronome/metronome.cfg.lua /etc/metronome/
            if [ -f "/etc/yunohost/current_host" ]; then
                DOMAIN=$(cat /etc/yunohost/current_host)
                sed -i "s/yunohost.org/$DOMAIN/g" /etc/metronome/metronome.cfg.lua
            fi
        fi
    ;;
    abort-upgrade|abort-remove|abort-deconfigure)
    ;;
    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#
