#!/bin/bash

HOSTNAME=$(hostname -f)

TMP="/usr/share/yunohost/yunohost-config/dspam"

function randpass() {
  [ "$2" == "0" ] && CHAR="[:alnum:]" || CHAR="[:graph:]"
    cat /dev/urandom | tr -cd "$CHAR" | head -c ${1:-32}
    echo
}

#DSPAM
if [ ! -d /var/spool/postfix/dspam ];
then
        mkdir /var/spool/postfix/dspam
        chown dspam: /var/spool/postfix/dspam
fi

if [ ! -f /etc/yunohost/yunohost.conf ] || [ $(grep dspam /etc/yunohost/yunohost.conf | cut -d= -f2) = "no" ];
then
	PATHLIBHASH="$(dpkg -L libdspam7-drv-hash | grep libhash_drv.so$ -m1)"
	cp $TMP/{default.prefs,dspam.conf} /etc/dspam
	sed -i "s@PATHLIBHASH@$PATHLIBHASH@" /etc/dspam/dspam.conf
	cp $TMP/extlookup.conf /etc/dspam/dspam.d/
fi

dpkg -l | grep yunohost-config-amavis > /dev/null 2>&1
if [[ ! $? -eq 0 ]];
then
	sed -i 's/START=no/START=yes/' /etc/default/dspam
	service dspam restart > /dev/null 2>&1
fi
