#!/bin/bash

set -e

case "$1" in
	remove|purge)
	rm /etc/dspam/{dspam.conf,default.prefs}
	;;

	upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
	;;

	*)
	echo "postrm called with unknown argument \`$1'" >&2
	exit 1
	;;
esac

exit 0
