#! /bin/sh
### BEGIN INIT INFO
# Provides:          udiskie
# Required-Start:    $local_fs $remote_fs $network $syslog
# Required-Stop:     $local_fs $remote_fs $network $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start/stop Udiskie Daemon
### END INIT INFO

DAEMON=/usr/local/bin/udiskie
DAEMON_OPTS="--suppress --file-manager=ls"

test -x $DAEMON || exit 0

. /lib/lsb/init-functions

logger "Udiskie: Start script executed"

case "$1" in
  start)
    logger "Udiskie Daemon: Starting"
    echo -n "Starting disk daemon: "
    start-stop-daemon --start --quiet --background --pidfile /var/run/udiskie.pid --make-pidfile \
        --exec $DAEMON -- $DAEMON_OPTS || true
    echo "udiskie."
    ;;
  stop)
    logger "Udiskie Daemon: Stopping"
    echo -n "Stopping disk daemon: "
    start-stop-daemon --stop --quiet --pidfile /var/run/udiskie.pid \
        --exec $DAEMON || true
    echo "udiskie."
    ;;
  restart)
    logger "Udiskie Daemon: Restarting"
    echo -n "Restarting disk daemon: "
    start-stop-daemon --stop --quiet --pidfile /var/run/udiskie.pid \
        --exec $DAEMON || true
    sleep 1
    start-stop-daemon --start --quiet --background --pidfile /var/run/udiskie.pid --make-pidfile \
        --exec $DAEMON -- $DAEMON_OPTS || true
    echo "udiskie."
    ;;
  *)
    logger "Udiskie Daemon: Invalid usage"
    echo "Usage: /etc/init.d/udiskie {start|stop|restart}" >&2
    exit 1
    ;;
esac

exit 0
