#! /bin/sh
### BEGIN INIT INFO
# Provides:          udiskie
# Required-Start:    $local_fs $remote_fs $network $syslog
# Required-Stop:     $local_fs $remote_fs $network $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start/stop Udiskie Daemon
### END INIT INFO

DAEMON=/usr/bin/udiskie
DAEMON_OPTS="--suppress --file-manager=ls"

test -x $DAEMON || exit 0

. /lib/lsb/init-functions

logger "Udiskie: Start script executed"

case "$1" in
  start)
    logger "Udiskie Daemon: Starting"
    log_daemon_msg "Starting disk daemon: udiskie"
    start-stop-daemon --start --quiet --background --pidfile /var/run/udiskie.pid --make-pidfile \
        --exec $DAEMON -- $DAEMON_OPTS
    log_end_msg $?
    ;;
  stop)
    logger "Udiskie Daemon: Stopping"
    log_daemon_msg "Stopping disk daemon: udiskie"
    kill `cat /var/run/udiskie.pid > /dev/null 2>&1` > /dev/null 2>&1
    rm /var/run/udiskie.pid > /dev/null 2>&1
    log_end_msg $?
    ;;
  restart)
    logger "Udiskie Daemon: Restarting"
    log_daemon_msg "Restarting disk daemon: udiskie"
    kill `cat /var/run/udiskie.pid > /dev/null 2>&1` > /dev/null 2>&1
    rm -f /var/run/udiskie.pid > /dev/null 2>&1
    start-stop-daemon --start --quiet --background --pidfile /var/run/udiskie.pid --make-pidfile \
        --exec $DAEMON -- $DAEMON_OPTS
    log_end_msg $?
    ;;
  *)
    logger "Udiskie Daemon: Invalid usage"
    echo "Usage: /etc/init.d/udiskie {start|stop|restart}" >&2
    exit 1
    ;;
esac

exit 0
