#!/bin/bash

HOSTNAME=$(hostname -f)

TMP="/usr/share/yunohost/yunohost-config/dovecot"

function randpass() {
  [ "$2" == "0" ] && CHAR="[:alnum:]" || CHAR="[:graph:]"
    cat /dev/urandom | tr -cd "$CHAR" | head -c ${1:-32}
    echo
}


if [ -f /etc/yunohost/current_host ];
then
        DOMAIN=$(cat /etc/yunohost/current_host)
        find $TMP -type f -exec sed -i "s/yunohost.org/$DOMAIN/g" {} \;
fi

if [ -f /etc/dovecot/global_script ];
then
	rm /etc/dovecot/global_script
fi

if [ ! -d /etc/dovecot/global_script/ ];
then
        mkdir /etc/dovecot/global_script/
fi

#Dovecot
if [ ! -f /etc/yunohost/yunohost.conf ] || [ $(grep dovecot /etc/yunohost/yunohost.conf | cut -d= -f2) = "no" ];
then
	adduser --system --ingroup mail --uid 500 vmail
	cp $TMP/sa-learn-pipe.sh /usr/bin/sa-learn-pipe.sh
	chmod +x /usr/bin/sa-learn-pipe.sh
	cp $TMP/{dovecot.conf,dovecot-ldap.conf,dovecot-ipv4.conf} /etc/dovecot/
	cp $TMP/global_script/dovecot.sieve /etc/dovecot/global_script
	if [ ! -f /proc/net/if_inet6 ];
	then
		mv /etc/dovecot/dovecot-ipv4.conf /etc/dovecot/dovecot.conf
	fi
	chown -R vmail:mail /etc/dovecot/global_script/
	chmod -R 770 /etc/dovecot/global_script/
	sievec /etc/dovecot/global_script/dovecot.sieve
	chmod +rw /etc/dovecot/global_script/dovecot.svbin
	service dovecot reload > /dev/null 2>&1
fi
