#! /bin/sh
### BEGIN INIT INFO
# Provides:          yunohost-api
# Required-Start:    $local_fs $remote_fs $network $syslog
# Required-Stop:     $local_fs $remote_fs $network $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start/stop YunoHost API
### END INIT INFO

DAEMON=/usr/bin/yunohost-api
DAEMON_OPTS=""

test -x $DAEMON || exit 0

. /lib/lsb/init-functions

logger "YunoHost API: Start script executed"

case "$1" in
  start)
    logger "YunoHost API: Starting"
    log_daemon_msg "Starting API: YunoHost"
    start-stop-daemon --start --quiet --background --pidfile /var/run/yunohost-api.pid --make-pidfile \
        --exec $DAEMON -- $DAEMON_OPTS
    log_end_msg $?
    ;;
  stop)
    logger "YunoHost API: Stopping"
    log_daemon_msg "Stopping API: YunoHost"
    kill `cat /var/run/yunohost-api.pid > /dev/null 2>&1` > /dev/null 2>&1
    rm /var/run/yunohost-api.pid > /dev/null 2>&1
    log_end_msg $?
    ;;
  restart)
    logger "YunoHost API: Restarting"
    log_daemon_msg "Restarting API: YunoHost"
    kill `cat /var/run/yunohost-api.pid > /dev/null 2>&1` > /dev/null 2>&1
    rm -f /var/run/yunohost-api.pid > /dev/null 2>&1
    start-stop-daemon --start --quiet --background --pidfile /var/run/yunohost-api.pid --make-pidfile \
        --exec $DAEMON -- $DAEMON_OPTS
    log_end_msg $?
    ;;
  status)
    logger "YunoHost API: Running"
    log_daemon_msg "YunoHost API: Running"
    cat /var/run/yunohost-api.pid > /dev/null 2>&1
    log_end_msg $?
    ;;
  *)
    logger "YunoHost API: Invalid usage"
    echo "Usage: /etc/init.d/yunohost-api {start|stop|restart|status}" >&2
    exit 1
    ;;
esac

exit 0
