#! /bin/sh
### BEGIN INIT INFO
# Provides:          yunohost-api
# Required-Start:    $local_fs $remote_fs $network $syslog
# Required-Stop:     $local_fs $remote_fs $network $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start/stop YunoHost API server
### END INIT INFO

. /lib/lsb/init-functions

logger "API: Start script executed"
API_SERVER_PATH="/usr/share/pyshared/yunohost-cli"
export PYTHONPATH="$API_SERVER_PATH:$PYTHONPATH"

case "$1" in
  start)
    logger "API Server: Starting"
    log_daemon_msg "Starting YunoHost" "API"
    cd $API_SERVER_PATH
    twistd -y yunohost.tac -l "/var/log/yunohost.log" --pidfile twistd.pid
    log_end_msg $?
    ;;
  stop)
    logger "API Server: Stopping"
    log_daemon_msg "Stopping YunoHost" "API"
    if [ -f $API_SERVER_PATH/twistd.pid ]; then
        kill `cat $API_SERVER_PATH/twistd.pid`
	rm $API_SERVER_PATH/twistd.pid
    fi
    log_end_msg $?
    ;;
  restart)
    logger "API Server: Restarting"
    log_daemon_msg "Restarting YunoHost" "API"
    if [ -f $API_SERVER_PATH/twistd.pid ]; then
        kill `cat $API_SERVER_PATH/twistd.pid`
	rm $API_SERVER_PATH/twistd.pid
    fi
    cd $API_SERVER_PATH
    twistd -y yunohost.tac -l "/var/log/yunohost.log" --pidfile twistd.pid
    log_end_msg $?
    ;;
  *)
    logger "API Server: Invalid usage"
    echo "Usage: /etc/init.d/yunohost-api {start|stop|restart}"
    exit 1
    ;;
esac

exit 0
