#!/bin/bash

## Allow users to access /media directory
#if [ ! -d /etc/skel/media ];
#then
#        mkdir -p /media
#	ln -s /media /etc/skel/
#fi
#
#update-rc.d udiskie defaults
#service dbus restart
#if [[ $? -eq 1 ]]; then
#    rm -f /var/run/dbus/system_bus_socket
#    service dbus restart
#fi
#service udiskie restart
