#!/bin/bash

HOSTNAME=$(hostname -f)

TMP="/usr/share/yunohost/yunohost-config"

function randpass() {
  [ "$2" == "0" ] && CHAR="[:alnum:]" || CHAR="[:graph:]"
    cat /dev/urandom | tr -cd "$CHAR" | head -c ${1:-32}
    echo
}

if [ -f /etc/yunohost/current_host ];
then
        DOMAIN=$(cat /etc/yunohost/current_host)
	find $TMP/others -type f -exec sed -i "s/yunohost.org/$DOMAIN/g" {} \;
else
	cp $TMP/others/current_host /etc/yunohost/current_host
fi

# Hosts
if ! grep -Fq "yunohost.org" /etc/hosts || ! grep -Fq "$DOMAIN" /etc/hosts
then
       cp $TMP/others/hosts /etc/
fi

# SSL
mkdir -p /usr/share/yunohost/yunohost-config/ssl/yunoCA/{ca,certs,crl,newcerts}
if [ ! -f /usr/share/ca-certificates/ca-yunohost_crt.pem ];
then
	if ! grep -Fq "ca-yunohost_crt.pem" /etc/ca-certificates.conf ; then
	echo "ca-yunohost_crt.pem" >> /etc/ca-certificates.conf
	fi
fi


#Iptables
cp $TMP/others/iptables /etc/init.d/
chmod +x /etc/init.d/iptables
update-rc.d iptables defaults
service iptables restart

#nssswitch
if ! grep -Fq "sudoers" /etc/nsswitch.conf ; then
echo -e "sudoers:\tldap files" >> /etc/nsswitch.conf
fi

#SSH
if [ ! -f /etc/yunohost/yunohost.conf ] || [ $(grep ssh /etc/yunohost/yunohost.conf | cut -d= -f2) = "no" ];
then
	cp $TMP/others/sshd_config* /etc/ssh/
        if [ ! -f /proc/net/if_inet6 ];
        then
                mv /etc/ssh/sshd_config-ipv4 /etc/ssh/sshd_config
        fi

	service ssh restart
fi

#Prompt
cp $TMP/others/boot_prompt.sh /etc/init.d/
chmod +x /etc/init.d/boot_prompt.sh
update-rc.d boot_prompt.sh defaults

#PAM
if [ ! -f /usr/share/pam-configs/my_mkhomedir ];
then
	cp $TMP/others/my_mkhomedir /usr/share/pam-configs/my_mkhomedir
	pam-auth-update --package
fi

#Admin confs
if [ ! -f /etc/yunohost/installed ];
then
	if [ ! -f /etc/yunohost/from_script ];
	then
		cp $TMP/others/bashrc /root/.bashrc
		cp $TMP/others/vimrc /root/.vimrc
	fi
fi

#Profile
if [ ! -f /etc/skel/.bashrc ];
then
	cp $TMP/others/bashrc /etc/skel/.bashrc
fi

if [ ! -f /etc/skel/.vimrc ];
then
	cp $TMP/others/vimrc /etc/skel/.vimrc
fi

#Others
cp $TMP/others/issue.net /etc/issue.net

#Root password
#if [ ! -f /etc/yunohost/yunohost-config/others/password ]; then
#	chage -d 0 root
#	touch /etc/yunohost/yunohost-config/others/password
#fi

#Unattended-upgrades
if grep -Fq "Unattended-Upgrade" /etc/apt/apt.conf.d/02periodic
then
	cp $TMP/unattended/* /etc/apt/apt.conf.d/
fi

#Firewall
if [ ! -f /etc/yunohost/firewall.yml ];
then
	cp $TMP/others/firewall.yml /etc/yunohost/
fi
