#!/bin/bash

TMP="/usr/share/yunohost/yunohost-config/nginx"

cp $TMP/ssowat.conf /etc/nginx/conf.d/
cp $TMP/yunohost_panel.conf.inc /etc/nginx/conf.d/
cp $TMP/yunohost_admin.conf.inc /etc/nginx/conf.d/
cp $TMP/yunohost_api.conf.inc /etc/nginx/conf.d/
cp $TMP/yunohost_admin.conf /etc/nginx/conf.d/

rm -f /etc/nginx/conf.d/ynhadmin.conf

if [ -f /etc/nginx/sites-enabled/default ];
then
	rm /etc/nginx/sites-enabled/default
fi

if [ ! -f /etc/yunohost/yunohost.conf ] || [ $(grep nginx /etc/yunohost/yunohost.conf | cut -d= -f2) = "no" ];
then
    if [ -f /etc/yunohost/installed ];
    then
        for FILE in $(ls /etc/nginx/conf.d/*.*.conf)
        do
            grep -q yunohost_admin $FILE
            if [[ ! $? -eq 0 ]];
            then
                DOMAIN=$(echo $FILE | sed 's@^/etc/nginx/conf.d/@@' | sed 's@.conf$@@')
                yunohost domain list --json | grep -q "\"$DOMAIN\""
                if [[ $? -eq 0 ]];
                then
                    cp $TMP/template.conf $FILE
                    sed -i "s@yunohost.org@$DOMAIN@g" $FILE
                fi
            fi
        done
        # yunohost.local server_name
        cp $TMP/yunohost_local.conf "/etc/nginx/conf.d/$(cat /etc/yunohost/current_host).d/"
    fi
fi
    

dpkg -l | grep openresty
if [[ $? -eq 0 ]]; then
    cp $TMP/openresty.conf /etc/nginx/conf.d/
fi

# Check IPv6 support
if [ ! -f /proc/net/if_inet6 ] || [ -z "$(nginx -V 2>&1 >/dev/null | grep "\-\-with\-ipv6")" ];
then
    # Comment IPv6 related conf lines
    sed -i '/^[ \t]*listen \[::\]:/s/^/#/' /etc/nginx/conf.d/*.conf
fi


if [ ! -f /etc/yunohost/installed ];
then
    service nginx restart
else
    service nginx restart > /dev/null 2>&1
fi
exit 0
