#!/bin/bash

DOMAIN=$(hostname -d)

HOSTNAME=$(hostname -f)

TMP="/usr/share/yunohost/yunohost-config/nginx"

function randpass() {
  [ "$2" == "0" ] && CHAR="[:alnum:]" || CHAR="[:graph:]"
    cat /dev/urandom | tr -cd "$CHAR" | head -c ${1:-32}
    echo
}

cp $TMP/ssowat.conf /etc/nginx/conf.d/

rm /etc/nginx/sites-enabled/default
