#!/bin/bash

TMP="/usr/share/yunohost/yunohost-config/nginx"

cp $TMP/ssowat.conf /etc/nginx/conf.d/
cp $TMP/yunohost_panel.conf.inc /etc/nginx/conf.d/
cp $TMP/yunohost_admin.conf.inc /etc/nginx/conf.d/
cp $TMP/yunohost_api.conf.inc /etc/nginx/conf.d/

rm -f /etc/nginx/conf.d/ynhadmin.conf

if [ ! -f /etc/yunohost/installed ];
then
        cp $TMP/yunohost_admin.conf /etc/nginx/conf.d/
fi

if [ -f /etc/nginx/sites-enabled/default ];
then
	rm /etc/nginx/sites-enabled/default
fi

if [ ! -f /etc/yunohost/yunohost.conf ] || [ $(grep nginx /etc/yunohost/yunohost.conf | cut -d= -f2) = "no" ];
then
    if [ ! -f /etc/yunohost/installed ];
    then
        for FILE in $(ls /etc/nginx/conf.d/*.*.conf)
        do
            grep -q yunohost_admin $FILE
            if [[ $? -eq 1 ]]
            then
                DOMAIN=$(echo $FILE | sed 's@^/etc/nginx/conf.d/@@' | sed 's@.conf$@@')
                cp $TMP/template.conf $FILE
                sed -i "s@yunohost.org@$DOMAIN@g" $FILE
            fi
        done
    fi
fi
    

dpkg -l | grep openresty
if [[ $? -eq 0 ]]; then
    cp $TMP/openresty.conf /etc/nginx/conf.d/
fi

service nginx restart > /dev/null 2>&1
exit 0
