#!/bin/bash

set -e

if [ -f /etc/init.d/yunohost-api ]; then
    # Do not restart old API
    grep -q "/usr/share/pyshared/yunohost-cli" /etc/init.d/yunohost-api
    if [[ ! $? -eq 0 ]];
    then
        service yunohost-api stop
#	nc -zv 127.0.0.1 6787 < /dev/null 2> /dev/null
#	if [[ ! $? -eq 0 ]];
#	then
#		exit 1
#	fi
    fi
fi

