#!/bin/bash

TMP="/usr/share/yunohost/yunohost-config"

/bin/bash $TMP/backup/configure_tahoe.sh

if [ ! -d /home/yunohost.backup ]; then
	mkdir /home/yunohost.backup
fi

if [ -d /home/yunohost.backup/tahoe ] && [ -f /etc/yunohost/yunohost.conf ] && [ $(grep backup /etc/yunohost/yunohost.conf | cut -d= -f2) = "no" ];
then
        cp $TMP/backup/tahoe.cfg /home/yunohost.backup/tahoe/
fi
