#!/bin/sh

set -e

case "$1" in
	remove|purge)
	rm /etc/amavis/conf.d/{15-content_filter_mode,20-debian_defaults,50-user}
	rm /etc/default/spamassassin
	rm /etc/spamassassin/local.cf
	;;

	upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
	;;

	*)
	echo "postrm called with unknown argument \`$1'" >&2
	exit 1
	;;
esac

exit 0
