#!/bin/sh

service metronome stop

set -e

#DEBHELPER#

if [ "$1" = "purge" ] ; then
    # Delete user 'metronome'
    deluser --quiet --system metronome > /dev/null || true
    
    # Delete directory for pid file
    if [ -d "/var/run/metronome" ]; then
    	rm -rf "/var/run/metronome";
    fi
    
    # Delete directory for log files
    if [ -d "/var/log/metronome" ]; then
    	rm -rf "/var/log/metronome";
    fi
fi
