#! /bin/sh
### BEGIN INIT INFO
# Provides:          tahoe-lafs
# Required-Start:    $local_fs $remote_fs $network $syslog
# Required-Stop:     $local_fs $remote_fs $network $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start/stop YunoHost API server
### END INIT INFO

. /lib/lsb/init-functions

logger "Tahoe: Start script executed"
TAHOE_PATH="/home/yunohost.backup/tahoe"

case "$1" in
  start)
    logger "Tahoe node: Starting"
    log_daemon_msg "Starting backup daemon" "Tahoe-LAFS"
    tahoe start $TAHOE_PATH > /dev/null
    log_end_msg $?
    ;;
  stop)
    logger "Tahoe node: Stopping"
    log_daemon_msg "Stopping backup daemon" "Tahoe-LAFS"
    tahoe stop $TAHOE_PATH > /dev/null
    log_end_msg $?
    ;;
  restart)
    logger "Tahoe node: Restarting"
    log_daemon_msg "Restarting backup daemon" "Tahoe-LAFS"
    tahoe stop $TAHOE_PATH > /dev/null 2>&1
    tahoe start $TAHOE_PATH > /dev/null
    log_end_msg $?
    ;;
  *)
    logger "Tahoe control: Invalid usage"
    echo "Usage: /etc/init.d/tahoe-lafs {start|stop|restart}"
    exit 1
    ;;
esac

exit 0
