#!/bin/bash

DOMAIN=$(hostname -d)

HOSTNAME=$(hostname -f)

TMP="/usr/share/yunohost/yunohost-config/apache2"

function randpass() {
  [ "$2" == "0" ] && CHAR="[:alnum:]" || CHAR="[:graph:]"
    cat /dev/urandom | tr -cd "$CHAR" | head -c ${1:-32}
    echo
}


find $TMP -type f -exec sed -i "s/DOMAIN/$DOMAIN/g" {} \;

#Apache2
a2enmod rewrite ssl perl headers proxy_http authnz_ldap
mkdir -p /var/www/yunohost
if [ ! -f /etc/yunohost/yunohost.conf ] || [ $(grep apache2 /etc/yunohost/yunohost.conf | cut -d= -f2) = "no" ];
then
        #cp $TMP/admin-lo /etc/apache2/sites-available/
        #cp $TMP/apache2.conf /etc/apache2/
        cp $TMP/yunohost.conf /etc/apache2/conf.d/
        #a2ensite handler admin-lo
        a2dissite default default-ssl
fi
chown -R www-data:www-data /var/www/yunohost/

#suPHP
cp /usr/share/yunohost/yunohost-config/suphp/suphp.conf /etc/suphp/suphp.conf
cp /usr/share/yunohost/yunohost-config/suphp/mods/suphp.conf /etc/apache2/mods-enabled/suphp.conf
if [ ! -d /usr/share/yunohost/admin ];
then
        mkdir -p /usr/share/yunohost/admin
fi
#chown -R yunohost-admin:yunohost-admin /usr/share/yunohost/admin

service apache2 reload
